### ISSUE TITLE
no screenshots

### ISSUE THREAD

**Issue by pogrammerx** [Contingencyy/VulkanRenderer#18]
would be a huge relieve if there where screenshots.

**Comment by Contingencyy** [comment]
As soon as there is something worth to screenshot, I will add them to the readme. I am still mostly figuring out how to set up the vulkan code and what extensions to use, the actual graphics features come later. I will start adding physically-based rendering within the next few days though.

**Comment by Contingencyy** [comment]
I've added a single screenshot now, showcasing physically-based rendering and normal mapping. I will keep the screenshots updated with the current progress from now on.
